// apps/react-example/src/App.tsx
import { SonicsProvider, useSound, useSonics, SonicsButton } from "sonics/react";
import { presets } from "sonics";

const wrap: React.CSSProperties = {
  fontFamily: "system-ui, sans-serif",
  maxWidth: 640,
  margin: "0 auto",
  padding: "48px 24px",
  color: "#eef0f4",
};
const btn: React.CSSProperties = {
  fontFamily: "ui-monospace, monospace",
  fontSize: 14,
  background: "#1a1a23",
  color: "#eef0f4",
  border: "1px solid #2d2d3a",
  borderRadius: 10,
  padding: "10px 16px",
  cursor: "pointer",
};

function Demo() {
  const { enabled, toggle, volume, setVolume } = useSonics();
  const save = useSound("click");

  return (
    <div style={wrap}>
      <h1 style={{ fontWeight: 640 }}>sonics · React</h1>
      <p style={{ color: "#9a9aab" }}>
        Every button below plays a synthesised sound. No audio files. Toggle sound off to see the
        provider mute everything.
      </p>

      <label style={{ display: "flex", gap: 8, alignItems: "center", margin: "20px 0" }}>
        <input type="checkbox" checked={enabled} onChange={toggle} /> Sound {enabled ? "on" : "off"}
      </label>

      <label style={{ display: "block", margin: "20px 0", color: "#9a9aab" }}>
        Volume {volume.toFixed(2)}
        <input
          type="range"
          min={0}
          max={1.2}
          step={0.01}
          value={volume}
          onChange={(e) => setVolume(parseFloat(e.target.value))}
          style={{ display: "block", width: 240, marginTop: 6 }}
        />
      </label>

      <h3>useSound hook</h3>
      <button style={btn} onClick={() => save()}>
        Save (click)
      </button>

      <h3 style={{ marginTop: 28 }}>SonicsButton, one per preset</h3>
      <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
        {(Object.keys(presets) as Array<keyof typeof presets>).map((name) => (
          <SonicsButton key={name} sound={name} style={btn}>
            {name}
          </SonicsButton>
        ))}
      </div>

      <h3 style={{ marginTop: 28 }}>Play on hover</h3>
      <SonicsButton sound="tick" on="hover" style={btn}>
        hover me
      </SonicsButton>
    </div>
  );
}

export default function App() {
  return (
    <SonicsProvider>
      <Demo />
    </SonicsProvider>
  );
}

// apps/vue-example/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { play, presets, armAutoUnlock, type Sound } from "sonics";

armAutoUnlock();

const names = Object.keys(presets) as Array<keyof typeof presets>;
const volume = ref(0.9);

function playPreset(name: keyof typeof presets) {
  play(name, { volume: volume.value });
}

const doorbell: Sound = {
  volume: 0.9,
  ticks: [
    { at: 0, gain: 0.5, freq: 2637, q: 8, decay: 0.006, tail: 0.9 },
    { at: 0.09, gain: 0.55, freq: 3520, q: 8, decay: 0.008, tail: 0.9 },
  ],
};
</script>

<template>
  <main>
    <h1>sonics · Vue</h1>
    <p>Every button plays a sound synthesised at runtime — no audio files loaded.</p>

    <div class="row">
      <button v-for="name in names" :key="name" @click="playPreset(name)">{{ name }}</button>
    </div>

    <label class="vol">
      volume {{ volume.toFixed(2) }}
      <input type="range" min="0" max="1.2" step="0.01" v-model.number="volume" />
    </label>

    <h3>Custom sound</h3>
    <button @click="play(doorbell, { volume })">play a doorbell spec</button>
  </main>
</template>

<style>
main {
  font-family: system-ui, sans-serif;
  max-width: 640px;
  margin: 0 auto;
  padding: 48px 24px;
  color: #0f0e12;
}
.row {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}
button {
  font-family: ui-monospace, monospace;
  font-size: 14px;
  background: #fff;
  border: 1px solid #0f0e12;
  padding: 9px 15px;
  cursor: pointer;
}
button:hover {
  background: #f05a24;
  color: #fff;
  border-color: #f05a24;
}
.vol {
  display: block;
  margin: 24px 0;
  font-family: ui-monospace, monospace;
  font-size: 13px;
}
</style>
